
#
# methods related to optimizing the sparse cholesky factorization
#


#
#' optimizing the sparse cholesky factorization
#'
#' @description Methods for optimizing the sparse cholesky factorization
#' @param object S4 class of type `run-output` typically generated by function `run`
#' @export
sparsity.tools <- function(object,spy=TRUE){
  if(! hasName(object@aux.info[[1]],"triplet_i")){
    exit("run-output does not contain sparse matrix info")
  }
  i <- object@aux.info[[1]]$triplet_i+1
  j <- object@aux.info[[1]]$triplet_j+1
  Li <- object@aux.info[[1]]$L_triplet_i+1
  Lj <- object@aux.info[[1]]$L_triplet_j+1
  n <- max(max(i),max(j))
  if(spy){
    par(mfrow=c(1,2))
    plot(j,i,xlim=c(1,n),ylim=c(n,1),pch=15,cex=0.5,main=paste("G, nz=",length(i)))
    plot(Lj,Li,xlim=c(1,n),ylim=c(n,1),pch=15,cex=0.5,main=paste("L, nz=",length(Li)))
  }
}



